name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  api-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env: 
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-api-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint source code with eslint
        run: npm run lint

  build-frontend:
    runs-on: ubuntu-latest
    needs: api-eslint
    defaults:
      run:
        working-directory: ./front
    env:
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-front-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Show repo files
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: |
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Check build output exists
        run: ls -la ./dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment: deploy
    env: 
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Copy files to server
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "SSH_PRIVATE_KEY is empty!"
          else
            echo "SSH_PRIVATE_KEY is set."
          fi

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP \
            "rm -rf ~/front/* && mkdir -p ~/front"
            
          scp -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -r ./front/dist/* $SERVER_USER@$SERVER_IP:~/front

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf ~/api/* && mkdir -p ~/api"

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes" \
            --exclude="node_modules" \
            --exclude="static" \
            --exclude=".git" \
            ./api/* $SERVER_USER@$SERVER_IP:~/api

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "pm2 restart backend"

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "cd api && npm ci"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.SERVER_USER }}