name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env: 
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Show repo files
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Show Hello World
        run: npm run hello-world

      - name: Lint source code with eslint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    env: 
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr '\\n' '\n' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 91.98.202.21 >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./ deployatron@91.98.202.21:~/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    