name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  api-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env: 
      NODE_VERSION: ${{ vars.NODE_VERSION }}
      RUN_ESLINT: ${{ !contains(github.event.head_commit.message, 'skip_eslint') }}
      MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4

      - name: Echo RUN_ESLINT
        run: |
          echo $RUN_ESLINT;

      - name: Skip notice
        if: env.RUN_ESLINT == 'false'
        run: echo "ESLint was skipped"

      - name: Cache node modules
        if: env.RUN_ESLINT == 'true'
        id: cache-api-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - uses: actions/setup-node@v4
        if: env.RUN_ESLINT == 'true'
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        if: env.RUN_ESLINT == 'true'
        run: npm ci

      - name: Lint source code with eslint
        if: env.RUN_ESLINT == 'true'
        run: npm run lint

  build-frontend:
    runs-on: ubuntu-latest
    needs: api-eslint
    defaults:
      run:
        working-directory: ./front
    env:
      NODE_VERSION: ${{ vars.NODE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-front-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Show repo files
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: |
          npm run build:prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Check build output exists
        run: ls -la ./dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment: deploy
    env: 
      NODE_VERSION: ${{ vars.NODE_VERSION }}
      APP_PATH: ${{ vars.APP_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Copy files to server
        run: |
          set -xe
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "pm2 stop $APP_PATH/ecosystem.config.js"

          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP \
            "rm -rf $APP_PATH/front/* && mkdir -p $APP_PATH/front"

          scp -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -r ./front/dist/* $SERVER_USER@$SERVER_IP:$APP_PATH/front

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf $APP_PATH/api/* && mkdir -p $APP_PATH/api"

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes" \
            --exclude="node_modules" \
            --exclude="static" \
            --exclude=".git" \
            ./api/* $SERVER_USER@$SERVER_IP:$APP_PATH/api

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "cd $APP_PATH/api && npm ci"

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "pm2 start $APP_PATH/ecosystem.config.js"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}