name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  api-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env: 
      NODE_VERSION: ${{ vars.NODE_VERSION }}
      RUN_ESLINT2: ${{ contains(github.event.head_commit.message, 'skip_eslint') == false }}
      MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4

      - name: Echo env.RUN_ESLINT2
        run: |
          echo ${{ env.RUN_ESLINT2 }}

      - name: Echo env.MESSAGE
        run: |
          echo ${{ env.MESSAGE }}

      - name: Determine if ESLint should run
        run: |
          if [[ "$(git log -1 --pretty=%B)" == *"skip_eslint"* ]]; then
            echo "RUN_ESLINT=false" >> $GITHUB_ENV
          else
            echo "RUN_ESLINT=true" >> $GITHUB_ENV
          fi

      - name: Skip ESLint if needed
        run: |
          echo "RUN_ESLINT=$RUN_ESLINT"
          if [ "$RUN_ESLINT" != "true" ]; then
            echo "ESLint skipped"
            exit 0
          fi

      - name: Cache node modules
        id: cache-api-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint source code with eslint
        run: npm run lint

  build-frontend:
    runs-on: ubuntu-latest
    needs: api-eslint
    defaults:
      run:
        working-directory: ./front
    env:
      NODE_VERSION: ${{ vars.NODE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-front-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Show repo files
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: |
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Check build output exists
        run: ls -la ./dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment: deploy
    env: 
      NODE_VERSION: ${{ vars.NODE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Copy files to server
        run: |
          set -xe
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP \
            "rm -rf ~/front/* && mkdir -p ~/front"

          scp -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -r ./front/dist/* $SERVER_USER@$SERVER_IP:~/front

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf ~/api/* && mkdir -p ~/api"

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes" \
            --exclude="node_modules" \
            --exclude="static" \
            --exclude=".git" \
            ./api/* $SERVER_USER@$SERVER_IP:~/api

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "cd api && npm ci"

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "pm2 restart backend"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}