name: staging-deploy

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    env:
      NODE_VERSION: ${{ vars.NODE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-front-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Show repo files
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: |
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Check build output exists
        run: ls -la ./dist
        
  deploy:
    if: "${{ !contains(github.event.pull_request.title, 'SKIP STAGING') }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: build-frontend
    environment: deploy
    env: 
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ vars.SERVER_IP }}
      SERVER_USER: ${{ vars.USER_NAME }}
      FRONT_HOST: ${{ vars.FRONT_HOST }}
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_TARGET_REF: ${{ github.base_ref }}
      APP_PATH: ${{ vars.APP_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Configure SSH connection
        run: |
          set -xe
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

      - name: Copy files to server
        run: |
          STAGING_PATH=$(echo "${GITHUB_HEAD_REF}-${GITHUB_TARGET_REF}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "STAGING_PATH=$STAGING_PATH" >> $GITHUB_ENV

          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "mkdir -p $APP_PATH/staging"

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf $APP_PATH/staging/$STAGING_PATH && mkdir -p $APP_PATH/staging/$STAGING_PATH/front"

          scp -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -r ./front/dist/* $SERVER_USER@$SERVER_IP:$APP_PATH/staging/$STAGING_PATH/front

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf $APP_PATH/staging/$STAGING_PATH/api/* && mkdir -p $APP_PATH/staging/$STAGING_PATH/api"

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes" \
            --exclude="node_modules" \
            --exclude="static" \
            --exclude=".git" \
            ./api/* $SERVER_USER@$SERVER_IP:$APP_PATH/staging/$STAGING_PATH/api

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "cd $APP_PATH/staging/$STAGING_PATH/api && npm ci"

      - name: Create db, user, generate dump
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}
          PG_HOST: ${{ vars.PG_HOST }}
          PG_PORT: ${{ vars.PG_PORT }}
          PG_SUPER_USER_NAME: ${{ secrets.PG_SUPER_USER_NAME }}
          PG_SUPER_USER_PASS: ${{ secrets.PG_SUPER_USER_PASS }}
          PG_PROD_USER_NAME: ${{ secrets.PG_PROD_USER_NAME }}
          PG_PROD_DB_NAME: ${{ secrets.PG_PROD_DB_NAME }}
          PG_PROD_USER_PASS: ${{ secrets.PG_PROD_USER_PASS }}
          PG_STAGING_USER_PASS: ${{ secrets.PG_STAGING_USER_PASS }}
        run: |
          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes \
            $SERVER_USER@$SERVER_IP \
              "PG_HOST='$PG_HOST' \
              PG_PORT='$PG_PORT' \
              PG_SUPER_USER_NAME='$PG_SUPER_USER_NAME' \
              PG_SUPER_USER_PASS='$PG_SUPER_USER_PASS' \
              PG_PROD_USER_NAME='$PG_PROD_USER_NAME' \
              PG_PROD_DB_NAME='$PG_PROD_DB_NAME' \
              PG_PROD_USER_PASS='$PG_PROD_USER_PASS' \
              STAGING_NAME='$STAGING_PATH' \
              PG_STAGING_USER_PASS='$PG_STAGING_USER_PASS' \
              APP_PATH='$APP_PATH' \
              bash $APP_PATH/bin/create_db_and_import.sh"

      - name: Run staging backend (api)
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}
          PG_HOST: ${{ vars.PG_HOST }}
          PG_PORT: ${{ vars.PG_PORT }}
          PG_STAGING_USER_PASS: ${{ secrets.PG_STAGING_USER_PASS }}
        run: |
          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes \
            $SERVER_USER@$SERVER_IP \
              "PG_HOST='$PG_HOST' \
              PG_PORT='$PG_PORT' \
              STAGING_NAME='$STAGING_PATH' \
              APP_PATH='$APP_PATH' \
              PG_STAGING_USER_PASS='$PG_STAGING_USER_PASS' \
              bash $APP_PATH/bin/create_pm2_config.sh"

      - name: Verify
        run: echo "STAGING PATH is $STAGING_PATH"

      - name: Add staging url to comments
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            âœ… This PR has been deployed to staging: https://${{ env.STAGING_PATH }}.${{ env.FRONT_HOST }}/

    