name: staging-cleanup

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: deploy
    env: 
      NODE_VERSION: ${{ vars.NODE_VERSION }}
      APP_PATH: ${{ vars.APP_PATH }}
    steps:
      - name: Remove staging files from server
        run: |
          set -xe
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

          STAGING_PATH=$(echo "${GITHUB_HEAD_REF}-${GITHUB_TARGET_REF}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "STAGING_PATH=$STAGING_PATH" >> $GITHUB_ENV

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf $APP_PATH/staging/$STAGING_PATH"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_TARGET_REF: ${{ github.base_ref }}
    
      - name: Cleanup db
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}
          PG_HOST: ${{ vars.PG_HOST }}
          PG_PORT: ${{ vars.PG_PORT }}
          PG_SUPER_USER_NAME: ${{ secrets.PG_SUPER_USER_NAME }}
          PG_SUPER_USER_PASS: ${{ secrets.PG_SUPER_USER_PASS }}
          PG_PROD_USER_NAME: ${{ secrets.PG_PROD_USER_NAME }}
          PG_PROD_DB_NAME: ${{ secrets.PG_PROD_DB_NAME }}
          PG_PROD_USER_PASS: ${{ secrets.PG_PROD_USER_PASS }}
          PG_STAGING_USER_PASS: ${{ secrets.PG_STAGING_USER_PASS }}
        run: |
          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes \
            $SERVER_USER@$SERVER_IP \
              "PG_HOST='$PG_HOST' \
              PG_PORT='$PG_PORT' \
              PG_SUPER_USER_NAME='$PG_SUPER_USER_NAME' \
              PG_SUPER_USER_PASS='$PG_SUPER_USER_PASS' \
              PG_PROD_USER_NAME='$PG_PROD_USER_NAME' \
              PG_PROD_DB_NAME='$PG_PROD_DB_NAME' \
              PG_PROD_USER_PASS='$PG_PROD_USER_PASS' \
              STAGING_NAME='$STAGING_PATH' \
              PG_STAGING_USER_PASS='$PG_STAGING_USER_PASS' \
              APP_PATH='$APP_PATH' \
              bash $APP_PATH/bin/cleanup_db_and_user.sh"