name: staging-deploy

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    env:
      NODE_VERSION: 18.19.1
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-front-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Show repo files
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: |
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Check build output exists
        run: ls -la ./dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment: deploy
    env: 
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ vars.SERVER_IP }}
      SERVER_USER: ${{ vars.USER_NAME }}
      FRONT_HOST: ${{ vars.FRON_HOST }}
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_TARGET_REF: ${{ github.base_ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Get PR number
        id: pr
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.pull_request.number;

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./front/dist

      - name: Copy files to server
        run: |
          set -xe
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

          STAGING_PATH=$(echo "${GITHUB_HEAD_REF}-${GITHUB_TARGET_REF}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "STAGING_PATH=$STAGING_PATH" >> $GITHUB_ENV

          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "mkdir -p ~/staging"

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP \
            "rm -rf ~/staging/$STAGING_PATH && mkdir -p ~/staging/$STAGING_PATH"

          scp -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -r ./front/dist/* $SERVER_USER@$SERVER_IP:~/staging/$STAGING_PATH

          echo "staging_path=$STAGING_PATH" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER);
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'âœ… This PR has been deployed to the staging: https://${process.env.STAGING_PATH}.${process.env.FRONT_HOST}/'
            })
        env:
          PR_NUMBER: ${{ steps.pr.outputs.result }} 

      - name: Add label to PR
        if: success() && steps.pr.outputs.result
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: deployed-to-staging
          issue_number: ${{ steps.pr.outputs.result }}


    