name: staging-reset-db

on:
  workflow_dispatch:

jobs:
  calculate-staging-path:
    runs-on: ubuntu-latest
    outputs:
      staging_path: ${{ steps.setpath.outputs.staging_path }}
    steps:
      - name: Set global env var
        id: setpath
        run: |
          VAL=$(echo "${GITHUB_HEAD_REF}-${GITHUB_BASE_REF}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "staging_path=$VAL" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: 
      calculate-staging-path
    environment: deploy
    env: 
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ vars.SERVER_IP }}
      SERVER_USER: ${{ vars.USER_NAME }}
      FRONT_HOST: ${{ vars.FRONT_HOST }}
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_TARGET_REF: ${{ github.base_ref }}
      APP_PATH: ${{ vars.APP_PATH }}
      STAGING_PATH: ${{ needs.calculate-staging-path.outputs.staging_path }}
    steps:
      - name: Configure SSH connection
        run: |
          set -xe
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes $SERVER_USER@$SERVER_IP "echo Connected!"

      - name: Create db, user, generate dump
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_USER: ${{ vars.USER_NAME }}
          PG_HOST: ${{ vars.PG_HOST }}
          PG_PORT: ${{ vars.PG_PORT }}
          PG_SUPER_USER_NAME: ${{ secrets.PG_SUPER_USER_NAME }}
          PG_SUPER_USER_PASS: ${{ secrets.PG_SUPER_USER_PASS }}
          PG_PROD_USER_NAME: ${{ secrets.PG_PROD_USER_NAME }}
          PG_PROD_DB_NAME: ${{ secrets.PG_PROD_DB_NAME }}
          PG_PROD_USER_PASS: ${{ secrets.PG_PROD_USER_PASS }}
          PG_STAGING_USER_PASS: ${{ secrets.PG_STAGING_USER_PASS }}
          APP_PATH: ${{ vars.APP_PATH }}
        run: |
          pm2 stop $STAGING_PATH

          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes \
            $SERVER_USER@$SERVER_IP \
              "PG_HOST='$PG_HOST' \
              PG_PORT='$PG_PORT' \
              PG_SUPER_USER_NAME='$PG_SUPER_USER_NAME' \
              PG_SUPER_USER_PASS='$PG_SUPER_USER_PASS' \
              PG_PROD_USER_NAME='$PG_PROD_USER_NAME' \
              PG_PROD_DB_NAME='$PG_PROD_DB_NAME' \
              PG_PROD_USER_PASS='$PG_PROD_USER_PASS' \
              STAGING_NAME='$STAGING_PATH' \
              PG_STAGING_USER_PASS='$PG_STAGING_USER_PASS' \
              APP_PATH='$APP_PATH' \
              bash $APP_PATH/bin/restore_db_from_dump.sh"

            pm2 start $STAGING_PATH;

      - name: Add staging url to comments
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ðŸ”„ Database has been reset to the initial state
          allow-repeats: true

    